### ISSUE TITLE
Failed to compile. Cannot find file './aws-exports' in './src'

### ISSUE THREAD

**Issue by bryanwills** [roblittle/weddingsite#1]
I am trying to find ideas for my own wedding website and I ran across this repo on Github and tried to download, compile and run the site locally on my computer and I get the following error:

```
     ~/code/wedding/bilinualreact     master !1 ❯ yarn build         ✔  system    16.7.0    0.1.0   09.27.21   2:35:39 
yarn run v1.22.11
$ react-scripts build
(node:85836) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/bryanwills/code/wedding/bilinualreact/node_modules/postcss-safe-parser/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
Creating an optimized production build...
Failed to compile.

./src/index.js
Cannot find file './aws-exports' in './src'.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have tried to troubleshoot this a few times and was unsuccessful, I am still very new to React, Next and a few other JavaScript frameworks. Tried to compile and run the site on a virtual environment as well and had the same issue. 

npm install, npm build and yarn install, yarn build created the same errors with the missing .aws-exports module.

**Comment by roblittle** [comment]
i'm still writing it, but the aws stuff you won't have.  i recommend following the guides online from Amazon/AWS on deploying a React SPA on Amplify using amplify tools.   It'll save you a lot of pain.  once you get that aws/amplify/react guide/tutorial up, if you take my repos code at that point, you should have more success. 
hth
